/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDatePicker: typeof import('./src/components/common/form-fields/base-date-picker.vue')['default']
    BaseInput: typeof import('./src/components/common/form-fields/base-input.vue')['default']
    BaseSelect: typeof import('./src/components/common/form-fields/base-select.vue')['default']
    DatePicker: typeof import('./src/components/common/form-fields/date-picker.vue')['default']
    DeleteEmployee: typeof import('./src/components/view/delete-employee.vue')['default']
    EmployeeDetail: typeof import('./src/components/view/employee-detail.vue')['default']
    EmployeeList: typeof import('./src/components/view/employee-list.vue')['default']
    FamilyMember: typeof import('./src/components/view/family-member.vue')['default']
    FamilyMemberArray: typeof import('./src/components/view/family-member-array.vue')['default']
    FieldArray: typeof import('./src/components/view/field-array.vue')['default']
    GlobalLoader: typeof import('./src/components/common/global-loader.vue')['default']
    NoEmployee: typeof import('./src/components/view/no-employee.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
