/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DeleteEmployee: typeof import('./src/components/view/delete-employee.vue')['default']
    EmployeeDetail: typeof import('./src/components/view/employee-detail.vue')['default']
    EmployeeList: typeof import('./src/components/view/employee-list.vue')['default']
    FamilyMember: typeof import('./src/components/view/family-member.vue')['default']
    GloabalLoader: typeof import('./src/components/common/global-loader.vue')['default']
    GlobalLoader: typeof import('./src/components/common/global-loader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
